name: Reusable Workflow Caller

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Reusable-caller-job-build-and-upload:
    uses: ./.github/workflows/reusable-upload.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  Reusable-caller-job-deploy:
    needs: Reusable-caller-job-build-and-upload
    uses: ./.github/workflows/reusable-deploy.yml
